client_config_backend: settings
client_config:
  client_id: 33463020419-4264trfqcl20vgen5qerie48jlmodn33.apps.googleusercontent.com
  client_secret: ahuXYYUYN3pYhlV-I13-E4rR

save_credentials: True
save_credentials_backend: file
save_credentials_file: credentials.json

get_refresh_token: True

oauth_scope:
  - https://www.googleapis.com/auth/drive.file
  - https://www.googleapis.com/auth/drive.install